[MAIN]

    SOL_RPC_URL = "https://api.mainnet-beta.solana.com"  # Solana RPC ( https://api.mainnet-beta.solana.com )

    MAX_RETRIES = 3 # Максимальное кол-во попыток сделать запрос/транзакцию если они фейлятся

    NEXT_ADDRESS_WAIT_TIME = [1, 5]  # Время ожидания в секундах между стартом выполнением разных акков рандомное в указанном диапазоне 

    NEXT_TX_WAIT_TIME = [30, 50] # Время ожидания между действиями одного аккаунта (в секундах)

[SWAP]

    # "SOL", "USDC", "USDT", "JUP", "BONK", 'ZEUS', 'PRCL'

    SWAP_FROM = ["USDC", "USDT"]
    SWAP_TO = ["USDT", "USDC"]

    TX_COUNT = [2, 2] # Количество свапов на каждый аккаунт рандомное в указанном диапазоне

    BALANCE_MIN_AMOUNT = 0.01 # Минимальное количество токена, которую ищет скрипт среди списка SWAP_FROM

    SWAP_AMOUNT_PERCENT = [1, 2] # Сколько процентов от баланса свапать. Рандомизируется в пределах погрешности
    
    SLIPPAGE_BPS = 50 # slippage в битах


